### ISSUE TITLE
Prototipação > [Planejamento inicial] Escolher a paleta de cores para o projeto

### ISSUE THREAD

**Issue by danieleolivs** [FLuiz22/ufroad-design#1]
# OVERVIEW
Buscar opções de paleta de cores que se adequem a identidade visual buscada para o projeto.

# TASKS
- [x] Selecionar opções de cores
- [x] Organizar na página do figma 
- [x] Mostrar as opções para votação
