### ISSUE TITLE
Prototipação > [Planejamento inicial] Escolher fonte para o projeto

### ISSUE THREAD

**Issue by danieleolivs** [FLuiz22/ufroad-design#2]
# OVERVIEW
Buscar opções de fontes que poderão ser usadas no sistema.

# TASKS
- [x] Selecionar opções de fontes para títulos
- [x] Selecionar opções de fontes para subtítulos
- [x] Selecionar opções de fontes para a descrição de textos
