### ISSUE TITLE
Prototipação > [Planejamento inicial] Criação da identidade visual (logo)

### ISSUE THREAD

**Issue by danieleolivs** [FLuiz22/ufroad-design#3]
# OVERVIEW
Buscar inspiração de logos e criar a primeira versão de logo para o sistema.

# TASKS
- [x] Selecionar inspiração de logos e apresentar no figma
- [x] Criar a primeira versão 
- [x] Apresentar para votação
