### ISSUE TITLE
Prototipação > [Planejamento inicial] Criação da tela de login

### ISSUE THREAD

**Issue by danieleolivs** [FLuiz22/ufroad-design#4]
# OVERVIEW
Criar a tela de login de usuário e adm do sistema.

# TASKS
- [x] Buscar inspiração a apresentar no figma
- [x] Organizar a estruturação da página (disposição dos itens)
- [x] Organizar a tela de login (plano de fundo) @alinebmr 
- [x] Organizar frame que contém as informações de login @Paulo-Lunguinho 
- [x] Apresentar o resultado para os membros do projeto
