### ISSUE TITLE
Prototipação: Refatoração da tela home

### ISSUE THREAD

**Issue by danieleolivs** [FLuiz22/ufroad-design#7]
# OVERVIEW

Refatorar a tela home do sistema.

# TASKS
- [ ] Criar a estrutura base (disposição dos itens)
- [ ] Criar o plano de fundo 
- [ ] Personalizar ícones/ilustrações
- [ ] Apresentar resultados
